### ISSUE TITLE
react-core is not installed?

### ISSUE THREAD

**Issue by zabojad** [haxe-react/react-native#16]
Hey !

I finally have the occasion to use your lib to do some RN with Haxe.

After the first setup, I'm getting this when trying to compile some sample code :

```
$ haxe dev.hxml 
Error: Error: Library react-core is not installed : run 'haxelib install react-core'
$ haxelib install react-core
Error: No such Project : react-core
```

What is this `react-core` lib ?

**Comment by zabojad** [comment]
I've installed `haxe-react-native` by cloning it and `haxelib dev` it...
```
$ haxelib list
...
react-native: [dev:/Users/thomasfetiveau/wksp_haxelib/haxe-react-native]
...
react: [dev:/Users/thomasfetiveau/wksp_haxelib/haxe-react]
```

**Comment by zabojad** [comment]
PS 2:

And my hxml is just:
```
-lib react
-lib react-native

-cp src
-main myapp.Boot
-js bin/index.js
```

**Comment by kevinresol** [comment]
Sorry, this lib now depends on https://github.com/haxe-react/haxe-react-core
you need to manually install it by `haxelib git react-core https://github.com/haxe-react/haxe-react-core`

**Comment by zabojad** [comment]
OK thanks for your fast answer.

What are the implications of using this `haxe-react-core` lib? Why can't it be merged in the main `haxe-react` lib?

**Comment by kevinresol** [comment]
Yeah we should probably do that. But I don't even remember the reason now, maybe I just needed a quick way to spin off some code at the time.

**Comment by kevinresol** [comment]
react-core is gone now
