### ISSUE TITLE
jsx applied to custom component causes invariant violation.

### ISSUE THREAD

**Issue by serjek** [haxe-react/react-native#18]
_Expected ref to be a function or a string_ error appears when trying ```jsx(<CustomScene/>);```
Registering CustomScene as app will work fine; jsx of some default component (say, ```View```) also works fine. Problem is with custom components that extend ReactComponent in haxe.

**Comment by serjek** [comment]
Turns out that adding ```ref=""``` to component like this ```jsx(<CustomScene ref=""/>);``` solves the issue, although this is not obvious, so I'm keeping issue open.

**Comment by kevinresol** [comment]
The jsx macro has changed a lot and let me assume this is obsolete.
